### ISSUE TITLE
Question about GIB in notebook

### ISSUE THREAD

**Issue by ChenyangWang95** [kkroy2/HIBPool#1]
Hi,

In the notebook, I am supposed to import GIB to use some functions. So, where could I obtain the GIB.py?
![image](https://user-images.githubusercontent.com/82666466/171320284-0b91eef7-517a-4fff-b54c-df1f2e9faa51.png)

Thanks very much!

**Comment by SunYukuan** [comment]
> Hi,
> 
> In the notebook, I am supposed to import GIB to use some functions. So, where could I obtain the GIB.py? ![image](https://user-images.githubusercontent.com/82666466/171320284-0b91eef7-517a-4fff-b54c-df1f2e9faa51.png)
> 
> Thanks very much!

Did you had solved it? I meet the same question, and another question is the function 
"posterior, _ = reparameterize(model=None, input=embs, mode='diag', size=dim)" is not found.
Thanks.

**Comment by RoyKashob** [comment]
GIB.py has been uploaded.
